#!/bin/bash

#SBATCH -J fig2
#SBATCH -p gpu
#SBATCH -o output_%j.txt
#SBATCH -e errortrace_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=danskora@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-task=1
#SBATCH --cpus-per-gpu=8
#SBATCH --mem=128G
#SBATCH --time=24:00:00
#SBATCH -A r00189

python mnist_experiment.py --experiment_name fig2 --dataset_size 60000 --batch_size 60000  --var_coef 0.2 --dataset MNIST --model MLP --exper 2 --lr 0 --epochs 500 --noise 0.0
