#!/bin/bash

#SBATCH -J fig3ghi
#SBATCH -p gpu
#SBATCH -o output_%j.txt
#SBATCH -e errortrace_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=danskora@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-task=1
#SBATCH --mem=32G
#SBATCH --time=48:00:00
#SBATCH -A r00189

python mnist_experiment.py --experiment_name fig3ghi --dataset_size 5000 --batch_size 500  --var_coef 0.000008 --dataset MNIST --model MLP --exper 3 --lr 0 --epochs 3000
