#!/bin/bash

#SBATCH -J gputest
#SBATCH -p gpu-debug
#SBATCH -o output_%j.txt
#SBATCH -e errortrace_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=danskora@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-task=1
#SBATCH --time=00:05:00
#SBATCH --mem=2G
#SBATCH -A r00189

module load python/gpu/3.10.5

python mnist_experiment.py --experiment_name gputest --epochs 500 --batch_size 500 --lr 0.01 --var 0.000004
